const express = require('express')
const app = express()
// const router = express.Router()
const bodyParser = require('body-parser')
const cors = require('cors')

app.use(cors())
app.use(bodyParser.json())

const consultRouter = require('./routes/consulta')
const vagasRouter = require('./routes/vagas')
const examRoutingRouter = require('./routes/exameEncaminhamento')
const localRouter = require('./routes/locais')
const examRouter = require('./routes/exame')
const routingRouter = require('./routes/encaminhamento')

app.use('/consult', consultRouter)
app.use('/vacancies', vagasRouter)
app.use('/examRouting', examRoutingRouter)
app.use('/places', localRouter)
app.use('/exam', examRouter)
app.use('/routing', routingRouter)

app.listen(process.env.PORT || 4001)
console.log(`MoreHealth ElasticSearchAPI listening on port ${process.env.PORT || 4001}`)